# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c7976fddb27f571b8bb25ea88c429bb2ee022079858fea8736ba9c88fe858c799eb71a15c9b4758cbf61463fdd5676576ea312165d24da168b5efcf1f1ad02

test:
  secret_key_base: 24377c33f51e0c8af557d21f0b5a6b9f97300ef59a008351eafa63856acccbd6dbe8fb7382fe186103bc5d8cf08edf216f9d85e71b2a5248ee88b94630b5878a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
